# Generated by Django 3.1 on 2021-03-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('domicilio', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('licencia_conducir', models.CharField(max_length=1)),
                ('tipo_contrato', models.CharField(choices=[('contrata', 'contrata'), ('indefinido', 'indefinido'), ('honorarios', 'honorarios')], max_length=10)),
                ('fecha_contrata', models.DateField(blank=True)),
                ('vigencia', models.DateField(blank=True)),
                ('contacto_emergencia', models.CharField(max_length=100)),
                ('telefono_emergencia', models.CharField(max_length=9)),
                ('grupo_sanguineo', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Felicitaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
            options={
                'verbose_name': 'Felicitaciones y Distincion',
                'verbose_name_plural': 'Felicitaciones y Distinciones',
                'ordering': ['empleado'],
            },
        ),
        migrations.CreateModel(
            name='Falta_Atraso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('motivo', models.CharField(max_length=200)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
            ],
            options={
                'verbose_name': 'Falta y/o atraso',
                'verbose_name_plural': 'Faltas y/o atrasos',
                'ordering': ['empleado'],
            },
        ),
    ]
